In [1]:
# dependencies
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
# load the file
path= r'..\redfin_analysis_mod.xlsx'
df = pd.read_excel(path)

In [3]:
df.head(2)

PRICE  DOWN PAYMENT  CLOSING COSTS  DOWN PAYMENT PERCENTAGE  \
0  379900        100000           1330                   26.323   
1  439000        100000           1536                   22.779   

   TOTAL MORTGAGE AMOUNT  MORTGAGE PAYMENT  TOTAL INTEREST COST  PMI  \
0                 281230              1343               202250    0   
1                 340536              1626               244824    0   

   PROPERTY TAXES  HOA    ...      ZIP CODE    LOCATION  LOT SIZE  YEAR BUILT  \
0            0.08   25    ...         20832  OLNEY OAKS    1870.0        1986   
1            0.09   80    ...         20164   TRAILSIDE    2614.0        1998   

   DAYS ON MARKET  STATUS      SOURCE          MLS   LATITUDE  LONGITUDE  
0               1  Active  BRIGHT MLS  MDMC2021332  39.155617 -77.074260  
1               1  Active  BRIGHT MLS  VALO2010804  38.998578 -77.425228  

[2 rows x 34 columns]

In [4]:
model = linear_model.LinearRegression(fit_intercept=True)
model.fit(df[['SQFT']],df.PRICE)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [5]:
print(model.coef_)
print(model.intercept_)

[30.06154923]
357392.0645244353


In [6]:
model.predict([[5000]])

array([507699.81066719])

# Save Using Python Pickle

In [7]:
import pickle

# used to serialize the python object into a file

In [8]:
# write to the file using pickle
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

**Load Saved Model**

In [9]:
# open the file 
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [10]:
mp.predict([[5000]])

array([507699.81066719])

# Save Using Joblib

In [11]:
# if the model uses a lot of numpy arrays, Joblib is better
from sklearn.externals import joblib

In [12]:
joblib.dump(model, 'model_joblib')

C:\Users\Hasan\Anaconda3\lib\site-packages\sklearn\externals\joblib\numpy_pickle.py:93: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  pickler.file_handle.write(chunk.tostring('C'))
C:\Users\Hasan\Anaconda3\lib\site-packages\sklearn\externals\joblib\numpy_pickle.py:93: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  pickler.file_handle.write(chunk.tostring('C'))


['model_joblib']

**Load Saved Model**

In [13]:
mj = joblib.load('model_joblib')

In [14]:
mj.predict([[5000]])

array([507699.81066719])